### ISSUE TITLE
Questions about stride param in resnet50 

### ISSUE THREAD

**Issue by HeimingX** [google/revisiting-self-supervised#3] opened 2019-09-04 03:32 UTC
Hi, thanks for the comprehensive review about recent SOTA self-supervised methods and the open source code. 

When I read the code of net arch part, I am a little bit confused about the stride param in resnet50(https://github.com/google/revisiting-self-supervised/blob/1eac8a76c1b002d74b4b2983739d2e0280f5a09c/models/resnet.py#L228). This param is set to 1 for the second to the final residual block which is different from the traditional resnet50 setting( https://github.com/tensorflow/models/blob/47e783e62a41f1f19baffc316d6530315ea872ac/official/resnet/keras/resnet_model.py#L106 ). Could you please help me for that? thanks a lot.

**Comment by akolesnikoff** [comment] 2019-09-04 11:23
After a quick look at our code and the code you referenced in appears to me that both codebases are consistent. Specifically, in the both of them the stride is applied in the first residual unit of each stage.

**Comment by lucasb-eyer** [comment] 2019-09-04 20:26
In our code, only the first block has stride 1, the three other have stride 2 (via `strides.pop()`). The same is for the `official/resnet/keras` code.
Another way you could quickly check that is by printing the shapes.
I'm closing the issue as this is not a bug, but please re-open with more arguments if you are convinced otherwise.

**Closed as completed by lucasb-eyer** 2019-09-04 20:26 UTC
